export const ERROR_CODES = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',
  NEW_PASSWORD_MUST_BE_DIFFERENT: 'NEW_PASSWORD_MUST_BE_DIFFERENT',
  UNAUTHORIZED: 'UNAUTHORIZED',

  INVALID_SESSION: 'INVALID_SESSION',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',

  FOOD_NOT_FOUND: 'FOOD_NOT_FOUND',
  FOOD_BAD_REQUEST: 'FOOD_BAD_REQUEST',

  AI_PARSE_FAILED: 'AI_PARSE_FAILED',

  SERVER_ERROR: 'SERVER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
